version: "3"
  
services:
  demo-xdbg:
    build:
      args:
        - WITH_XDEBUG=true
      context: .
      dockerfile: ./Dockerfile
    image: demo-xdbg
    container_name: demo-xdbg
    ports:
      - 80:80
    volumes:
       - ./:/var/www/html